name = "GeoAACGM"
uuid = "7d0bd8ea-8a67-4204-9dfc-7af11c683dec"
version = "0.1.3"
authors = ["Beforerr <zzj956959688@gmail.com> and contributors"]

[workspace]
projects = ["docs"]

[deps]
Bumper = "8ce10254-0962-460f-a3d8-1f77fea1446e"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
FixedSizeArrays = "3821ddf9-e5b5-40d5-8e25-6813ab96b5e2"
LazyArrays = "5078a376-72f3-5289-bfd5-ec5146d43c02"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
SphericalHarmonics = "c489a379-e885-57ff-9236-bd896d33c250"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"

[weakdeps]
GeoCotrans = "4624b3bc-fe35-44f8-bfa8-722ff9c0e307"
SpaceDataModel = "0b37b92c-f0c5-4a52-bd5c-390dec20857c"

[extensions]
GeoAACGMGeoCotransExt = "GeoCotrans"
GeoAACGMSpaceDataModelExt = "SpaceDataModel"

[compat]
Bumper = "0.7"
Dates = "1"
Dictionaries = "0.4"
FixedSizeArrays = "1"
GeoCotrans = "0.1"
LazyArrays = "2.6"
LinearAlgebra = "1"
PrecompileTools = "1.2"
SpaceDataModel = "0.2.3"
SphericalHarmonics = "0.1.19"
StaticArrays = "1.9"
Tullio = "0.3"
julia = "1.10"
