name = "Aacgm"
uuid = "7d0bd8ea-8a67-4204-9dfc-7af11c683dec"
authors = ["Beforerr <zzj956959688@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
LazyArrays = "5078a376-72f3-5289-bfd5-ec5146d43c02"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
SphericalHarmonics = "c489a379-e885-57ff-9236-bd896d33c250"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"

[compat]
Dates = "1"
Dictionaries = "0.4.5"
LazyArrays = "2.6.1"
LinearAlgebra = "1"
PrecompileTools = "1.2"
SphericalHarmonics = "0.1.19"
StaticArrays = "1"
Tullio = "0.3"
julia = "1.10"
